import {useId,useState} from 'react';
import states from '../geo/brazil-map.json';
import {Panel} from './Metrics.jsx';
import {distributeRegions} from '../regions.js';
import {formatNumber,rate} from '../report.js';
const labelOffsets={DF:[8,-5],RN:[22,-3],PB:[24,0],AL:[26,3],SE:[30,8],ES:[22,0],RJ:[14,8]};
export default function BrazilMap({snapshot,title='De onde vem seu público',unit='visitantes',context='Visitantes únicos por estado'}){
 const [selected,setSelected]=useState(null);
 const id=useId().replace(/:/g,''),counts=snapshot.demo?distributeRegions(snapshot.current.uniqueVisitors):snapshot.current.stateVisitors||{};
 const ranked=states.map(state=>({...state,count:counts[state.abbr]??0})).filter(state=>state.count>0).sort((a,b)=>b.count-a.count);
 const maximum=Math.max(...ranked.map(state=>state.count),1),located=ranked.reduce((sum,state)=>sum+state.count,0);
 const activeState=states.find(state=>state.abbr===selected),unknown=unit==='vendas'?null:Math.max(0,(snapshot.current.visits??0)-located);
 if(unit==='visitantes'&&snapshot.current.geographyUnit==='visitas'){unit='visitas';context='Visitas por estado';}
 return <Panel title={title} className="brazil-panel" action={<span className="panel-context">{context}</span>}><div className="brazil-layout">
 <div className="brazil-canvas"><svg viewBox="0 0 410 390" role="img" aria-label={'Brasil: '+formatNumber(located)+' '+unit+' com estado identificado. Todos os estados visíveis.'}>
 <defs><pattern id={'map-grid-'+id} width="26" height="26" patternUnits="userSpaceOnUse"><path d="M26 0H0V26" fill="none" stroke="#7227dc" strokeOpacity=".14" strokeWidth=".5"/></pattern></defs><rect width="410" height="390" fill={'url(#map-grid-'+id+')'}/>
 {states.map(state=><path key={state.abbr} className={'map-state'+(selected===state.abbr?' selected':'')} d={state.path} role="button" tabIndex="0" aria-label={state.name+': '+formatNumber(counts[state.abbr]||0)+' '+unit} aria-pressed={selected===state.abbr} onClick={()=>setSelected(current=>current===state.abbr?null:state.abbr)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setSelected(current=>current===state.abbr?null:state.abbr);}}} fill={counts[state.abbr]>0?'rgba(114,39,220,'+(.24+.66*counts[state.abbr]/maximum)+')':'#130c20'} stroke="#a270d8" strokeWidth=".75"><title>{state.name+' ('+state.abbr+'): '+formatNumber(counts[state.abbr]||0)+' '+unit+' com localização identificada'}</title></path>)}
 {states.map(state=>{const [dx,dy]=labelOffsets[state.abbr]||[0,0];return <g key={state.abbr} className="map-state-label" pointerEvents="none">{dx>10&&<line x1={state.point[0]} y1={state.point[1]} x2={state.point[0]+dx-5} y2={state.point[1]+dy} stroke="#ac87cd" strokeWidth=".65"/>}<text x={state.point[0]+dx} y={state.point[1]+dy+3} textAnchor="middle" fill={counts[state.abbr]>0?'#ffffff':'#b89bce'}>{state.abbr}</text></g>;})}
 </svg><p className="map-attribution">Malha: <a href="https://servicodados.ibge.gov.br/api/docs/malhas?versao=3" target="_blank" rel="noopener noreferrer">IBGE</a> · localização aproximada · <a href="https://db-ip.com" target="_blank" rel="noopener noreferrer">DB-IP</a> · base 10/2026</p></div>
 <div className="brazil-details"><p className="map-total"><strong>{formatNumber(located)}</strong><span>{unit} com estado identificado</span></p>{activeState&&<section className="selected-state" aria-live="polite"><div>Estado selecionado</div><h3>{activeState.abbr} · {activeState.name}<button type="button" aria-label="Limpar estado selecionado" onClick={()=>setSelected(null)}>×</button></h3><strong>{formatNumber(counts[activeState.abbr]||0)} {unit}</strong><p>{counts[activeState.abbr]>0?'Localização aproximada da conexão neste período.':`Nenhuma visita identificada em ${activeState.name} neste período.`}</p></section>}<ol className="state-ranking">{ranked.map((state,index)=><li key={state.abbr}><span className="rank-index">{index+1}</span><span className="state-name">{state.abbr} · {state.name}<span className="bar-track"><span className="bar-fill" style={{width:rate(state.count,maximum)+'%'}}/></span></span><strong>{formatNumber(state.count)}</strong></li>)}</ol>{unknown>0&&<p className="panel-note">{formatNumber(unknown)} visita(s) sem estado identificado; não são atribuídas a nenhum estado.</p>}<p className="panel-note">A intensidade indica o volume registrado no período. A localização é aproximada.</p></div>
 </div></Panel>;
}
