import {useState} from 'react';
import {Panel} from './Metrics.jsx';
function nowLocal(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());const get=t=>parts.find(p=>p.type===t).value;return get('year')+'-'+get('month')+'-'+get('day')+'T'+get('hour')+':'+get('minute');}
export default function ConfirmContact({demo,onConfirm,busy}){
 const [reference,setReference]=useState(''),[phone,setPhone]=useState(''),[quote,setQuote]=useState(false),[feedback,setFeedback]=useState(''),[receivedAt,setReceivedAt]=useState(nowLocal);
 async function submit(event){event.preventDefault();setFeedback('');try{await onConfirm({reference:reference.trim().toUpperCase(),phone,quote,receivedAt});setReference('');setPhone('');setQuote(false);setReceivedAt(nowLocal());setFeedback('Contato confirmado e compartilhado com a equipe.');}catch{setFeedback('Não foi possível confirmar. Confira o código, o telefone e a data. A mensagem precisa ter chegado nos sete dias de validade do código. Códigos compartilhados entre contatos precisam de revisão.');}}
 return <Panel title="Confirmar mensagem recebida"><p className="panel-note top-note">Use depois de conferir uma mensagem real no WhatsApp comum. Copie a referência enviada pelo cliente. Abrir o aplicativo ou clicar no botão não basta.</p>
 <form className="confirm-contact-form" onSubmit={submit}><label>Referência recebida<input required maxLength={50} placeholder="TS-LIVE-…" value={reference} onChange={e=>setReference(e.target.value)} autoComplete="off"/></label><label>Telefone de quem enviou<input required type="tel" value={phone} onChange={e=>setPhone(e.target.value)} autoComplete="off" placeholder="DDD + número"/></label><p className="panel-note">O telefone é usado no servidor para evitar contagens duplicadas. Ele não é armazenado nem exibido no painel.</p><label>Data da mensagem · horário de Brasília<input type="datetime-local" required value={receivedAt} onChange={e=>setReceivedAt(e.target.value)}/></label><label className="confirm-quote"><input type="checkbox" checked={quote} onChange={e=>setQuote(e.target.checked)}/>A pessoa pediu orçamento na conversa</label><button className="button primary" disabled={demo||busy}>Confirmar contato do site</button><p className="feedback" role="status">{demo?'Este registro será habilitado no painel conectado.':feedback}</p></form></Panel>;
}
