import {useEffect,useState} from 'react';
import {packageLabels,serviceLabels,stateLabels} from '../sales.js';
export default function OpportunityEditor({lead,onSave,onClose,busy=false,demo=false}){
 const [values,setValues]=useState({clientLabel:lead.client_label||'',phone:'',package:lead.selected_package||String(lead.package).toUpperCase(),customPackageName:lead.custom_package_name||'',service:lead.service_category||'unknown',state:lead.customer_state||'',city:lead.customer_city||''}),[error,setError]=useState('');
 const field=(key,value)=>setValues(current=>({...current,[key]:value}));
 useEffect(()=>{const previous=document.activeElement,dialog=document.querySelector('.opportunity-editor');dialog.querySelector('input')?.focus();const keyboard=event=>{if(event.key==='Escape'){event.preventDefault();onClose();}if(event.key==='Tab'){const targets=[...dialog.querySelectorAll('input,select,button')].filter(element=>!element.disabled),first=targets[0],last=targets.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}};dialog.addEventListener('keydown',keyboard);return()=>{dialog.removeEventListener('keydown',keyboard);previous?.focus();};},[]);
 async function submit(event){event.preventDefault();setError('');try{await onSave(lead.id,values);onClose();}catch(e){setError(e.message||'Não foi possível salvar os dados.');}}
 return <div className="dialog-backdrop"><section className="opportunity-editor" role="dialog" aria-modal="true" aria-labelledby="client-editor-title"><header><h2 id="client-editor-title">Dados do cliente e do pedido</h2><button className="icon-button" onClick={onClose} aria-label="Fechar cadastro do cliente">×</button></header><code>{lead.reference}</code><form onSubmit={submit} className="account-form"><div className="two-columns"><label>Nome ou apelido do cliente<input maxLength={80} value={values.clientLabel} onChange={e=>field('clientLabel',e.target.value)}/></label><label>Telefone para identificar o cliente<input type="tel" autoComplete="off" value={values.phone} onChange={e=>field('phone',e.target.value)} placeholder={lead.client_id?'Cliente já identificado':'DDD + número'}/></label></div><p className="panel-note">{demo?'Exemplo: nenhum dado real será salvo.':'O telefone gera um identificador privado. O número original não é salvo.'} {lead.client_id?'Deixe vazio para manter a identificação atual.':'Sem ele, o pedido aparece no total de oportunidades, mas não no total de clientes únicos.'}</p><div className="two-columns"><label>Serviço negociado<select value={values.service} onChange={e=>field('service',e.target.value)}>{Object.entries(serviceLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Pacote negociado<select value={values.package} onChange={e=>field('package',e.target.value)}>{Object.entries(packageLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div>{values.package==='CUSTOM'&&<label>Nome do pacote personalizado<input required maxLength={80} placeholder="Ex.: Setup + identidade visual" value={values.customPackageName} onChange={e=>field('customPackageName',e.target.value)}/></label>}<div className="two-columns"><label>Estado do cliente<select value={values.state} onChange={e=>field('state',e.target.value)}><option value="">Não informado</option>{Object.entries(stateLabels).sort((a,b)=>a[1].localeCompare(b[1],'pt-BR')).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Cidade do cliente<input maxLength={80} value={values.city} onChange={e=>field('city',e.target.value)} placeholder="Informe o local do cliente"/></label></div><p className="panel-note">A localização é informada durante o atendimento. O mapa de compras não usa a localização dos visitantes do site.</p><div className="button-row"><button className="button primary" disabled={busy}>{busy?'Salvando…':'Salvar dados do cliente'}</button><button type="button" className="button secondary" onClick={onClose}>Cancelar</button></div>{error&&<p className="auth-error" role="alert">{error}</p>}</form></section></div>;
}
