import {useState} from 'react';
import {Monitor,Instagram,Database,ExternalLink,ChevronDown,ShieldCheck} from 'lucide-react';
import {Panel} from '../components/Metrics.jsx';
import {WhatsAppIcon} from '../components/BrandIcons.jsx';
import {business} from '../data.js';
const connections=[
 {id:'website',title:'Métricas do site',icon:Monitor,subtitle:business.website,url:business.website,action:'Abrir site',steps:['A medição registra navegação, cliques e desempenho após o consentimento do visitante.','O mapa usa a localização aproximada do Google Analytics quando essa conexão estiver configurada. Visitantes sem estado conhecido não são distribuídos no mapa.','As referências dos botões do WhatsApp identificam a origem do contato. Um clique não confirma o envio da mensagem.']},
 {id:'instagram',title:'Instagram',icon:Instagram,subtitle:business.handle+' · conta de criador',url:'https://developers.facebook.com/apps/',action:'Abrir aplicativos Meta',steps:['Autorize a conta tuna.stream no aplicativo oficial da Meta com acesso às métricas. A conexão pelo Instagram Login não exige vincular uma Página do Facebook.','Tokens e renovação ficam no servidor. Não coloque credenciais na interface ou em mensagens do painel.','A coleta consulta a conta a cada quatro horas. Feed, Reels e Stories são separados; dados que a API não oferece permanecem indisponíveis.']},
 {id:'whatsapp',title:'Contatos pelo WhatsApp comum',icon:WhatsAppIcon,subtitle:'Referência do site + confirmação pela equipe',url:business.website,action:'Ver botões do site',steps:['O visitante abre o WhatsApp com uma referência única adicionada à mensagem. Ele ainda precisa enviar a mensagem.','Ao receber a mensagem, registre a referência, a data e o telefone na aba WhatsApp. O servidor guarda somente um identificador protegido para evitar duplicados.','Marque pedidos de orçamento e acompanhe as etapas compartilhadas. Mensagens sem referência válida não entram nos totais do site.','Para enviar automaticamente os dois relatórios em imagem, é necessária uma conexão oficial de envio e dois modelos aprovados. Enquanto isso, as imagens podem ser baixadas e compartilhadas.']},
 {id:'database',title:'Banco e acesso da equipe',icon:Database,subtitle:'Matheus P e Adriana S · usuário e senha',url:'https://lovable.dev/projects/61800de5-dce3-4499-91d0-8d8e1837cd2c',action:'Abrir projeto',steps:['Os dois acessos pertencem à mesma equipe. As regras do banco verificam a permissão antes de liberar informações.','As senhas ficam protegidas pelo serviço de autenticação. A interface não contém as senhas nem a chave administrativa.','Alterações do painel são compartilhadas pela conexão online. A coleta do site é consolidada aproximadamente a cada minuto; a origem de cada dado mostra sua atualização.']}
];
const labels={ready:'Conectado',pending:'Pendente',error:'Precisa de atenção'};
export default function Integrations({operations,demo}){
 const [expanded,setExpanded]=useState(null);
 return <><div className="setup-intro"><h2>Suas fontes de informação</h2><p>Consulte o estado da coleta e o que cada conexão permite medir.</p></div>
 <div className="integration-list">{connections.map(({id,title,icon:Icon,subtitle,url,action,steps})=>{const state=operations?.integrations.find(item=>item.source===id);return <section className="integration" key={id}><div className="integration-header"><div className="integration-icon"><Icon size={25}/></div><div className="integration-title"><h2>{title}</h2><p>{subtitle}</p></div><span className="connection-status"><i/>{demo?'Demonstração':id==='database'?'Acesso verificado':state?.mode==='manual'?'Confirmação manual':labels[state?.status]||'Pendente'}</span><button className="button secondary" aria-expanded={expanded===id} aria-controls={'guide-'+id} onClick={()=>setExpanded(expanded===id?null:id)}>Ver detalhes<ChevronDown size={16}/></button></div>{expanded===id&&<div className="integration-guide" id={'guide-'+id}><ol>{steps.map(step=><li key={step}>{step}</li>)}</ol><a href={url} className="button secondary" target="_blank" rel="noopener noreferrer">{action}<ExternalLink size={16}/></a></div>}</section>;})}</div>
 <div className="two-columns"><Panel title="Privacidade na coleta"><div className="inline-description"><ShieldCheck size={25} className="icon-mint"/><div><p>O painel não guarda o texto das mensagens nem exibe telefones de clientes. A referência e o identificador protegido permitem contar contatos distintos.</p><p className="panel-note">Pseudonimização não equivale a anonimização. A recusa da medição impede a coleta opcional de navegação.</p></div></div></Panel><Panel title="Atualização compartilhada"><p>Vocês consultam o mesmo banco pelo celular ou computador, com conexão à internet.</p><p className="panel-note">{demo?'Nesta prévia os valores são exemplos.':'A atualização do painel acompanha a coleta disponível. O Instagram depende do intervalo de consulta e do processamento da Meta.'} O envio automático de imagens só fica disponível quando a conexão de envio estiver configurada.</p></Panel></div></>;
}
