import {useEffect,useState} from 'react';
import {FileText,Clock3,Bell,Send,CircleCheck} from 'lucide-react';
import {Panel} from '../components/Metrics.jsx';
import {reportImageUrl} from '../lib/report-images.js';
const defaultSchedule={day:'1',time:'09:00'};
function readSchedule(){try{const s=JSON.parse(localStorage.getItem('tunastream-demo-schedule'));return s&&/^[0-6]$/.test(s.day)&&/^([01]\d|2[0-3]):[0-5]\d$/.test(s.time)?s:defaultSchedule;}catch{return defaultSchedule;}}
const statusLabels={queued:'Na fila',rendering:'Gerando imagem',sending:'Enviando',sent:'Aceito pela Meta',delivered:'Entregue',read:'Lido',failed:'Falhou',uncertain:'Aguardando confirmação'};
export default function Reports({snapshot,onReportOpen,operations}){
 const [schedule,setSchedule]=useState(snapshot.demo?readSchedule:()=>defaultSchedule),[feedback,setFeedback]=useState('');
 useEffect(()=>{if(!snapshot.demo&&operations?.schedule)setSchedule({day:String(operations.schedule.weekday),time:operations.schedule.send_time.slice(0,5)});},[snapshot.demo,operations?.schedule?.weekday,operations?.schedule?.send_time]);
 async function save(event){event.preventDefault();try{
  if(snapshot.demo){localStorage.setItem('tunastream-demo-schedule',JSON.stringify(schedule));setFeedback('Preferência de demonstração salva neste navegador.');}
  else{await operations.saveSchedule(schedule);setFeedback('Preferência salva para os dois acessos. '+(operations.schedule?.enabled?'Envio automático ativo.':'Envio pendente da configuração oficial.'));}
 }catch{setFeedback('Não foi possível salvar. Tente novamente.');}}
 async function send(){setFeedback('');try{const result=await operations.sendReport();setFeedback(result.results.every(r=>['sent','already_processed'].includes(r.status))?'As duas imagens foram processadas. Confira o status da entrega abaixo.':'O envio precisa de atenção. Confira o status abaixo.');}catch{setFeedback('Não foi possível enviar agora. Confira a conexão oficial.');}}
 return <div className="two-columns report-page"><Panel title="Relatórios em imagem"><div className="report-preview-heading"><FileText className="icon-purple" size={30}/><div><strong>{snapshot.period.label}</strong><p>Uma imagem do site. Outra do Instagram.</p></div></div><div className="report-image-pair">{['website','instagram'].map(type=><button key={type} className="report-thumbnail" onClick={onReportOpen} aria-label={'Ver imagem do '+(type==='website'?'site':'Instagram')}><img src={reportImageUrl(snapshot,type)} alt={'Prévia do relatório do '+(type==='website'?'site':'Instagram')}/></button>)}</div><button className="button primary" onClick={onReportOpen}><FileText size={17}/>Ver imagens e baixar PNG</button><p className="panel-note top-note">O envio semanal usa a última semana completa, de segunda a domingo. A prévia respeita o período selecionado.</p></Panel>
 <div className="stack"><Panel title="Quando receber"><p className="panel-note top-note">Segunda-feira às 09:00 é o horário inicial. Você pode ajustar abaixo.</p><form onSubmit={save} className="schedule-form"><label>Dia da semana<select value={schedule.day} onChange={e=>setSchedule({...schedule,day:e.target.value})}>{['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado'].map((d,i)=><option value={String(i)} key={d}>{d}</option>)}</select></label><label>Horário<input type="time" required value={schedule.time} onChange={e=>setSchedule({...schedule,time:e.target.value})}/></label><p className="timezone-note"><Clock3 size={16}/>Horário de Brasília</p><button className="button secondary" disabled={operations?.busy}><CircleCheck size={17}/>{snapshot.demo?'Salvar preferência local':'Salvar para a equipe'}</button><p className="feedback" role="status">{feedback}</p></form></Panel>
 <Panel title="Envio pelo WhatsApp"><p className="empty-explanation">{operations?.reportConfigured?'Conexão de envio configurada.':'A integração oficial ainda está pendente.'}</p><p className="panel-note">Duas mensagens com imagem, usando modelos aprovados pela Meta. O destinatário é definido no servidor.</p><button className="button secondary" onClick={send} disabled={snapshot.demo||!operations?.reportConfigured||operations?.busy}><Send size={17}/>Enviar as duas imagens</button>{operations?.error&&<p className="feedback" role="status">{operations.error}</p>}</Panel>
 <Panel title="Histórico de entrega">{operations?.deliveries.length?<div className="table-scroll"><table><thead><tr><th>Semana</th><th>Imagem</th><th>Status</th></tr></thead><tbody>{operations.deliveries.map(r=><tr key={r.period_start+r.report_type}><td>{r.period_start.split('-').reverse().join('/')}</td><td>{r.report_type==='website'?'Site':'Instagram'}</td><td>{statusLabels[r.status]||'Aguardando'}</td></tr>)}</tbody></table></div>:<div className="inline-description"><Bell size={22} className="icon-purple"/><p>Nenhuma entrega registrada. Aceite pela Meta, entrega e leitura terão status separados. Um envio sem confirmação não será repetido automaticamente.</p></div>}</Panel></div></div>;
}
