import {FileText,Clock3,Bell,Mail} from 'lucide-react';
import {Panel} from '../components/Metrics.jsx';
import {reportImageUrl} from '../lib/report-images.js';
const labels={preparing:'Preparando',sending:'Enviando',sent:'Aceito pelo Gmail',failed:'Falhou',uncertain:'Requer conferência'};
export default function Reports({snapshot,onReportOpen,operations}){
 const enabled=!snapshot.demo&&operations?.schedule?.email_reports_enabled;
 return <div className="two-columns report-page"><Panel title="Relatórios em imagem"><div className="report-preview-heading"><FileText className="icon-purple" size={30}/><div><strong>{snapshot.period.label}</strong><p>Uma imagem do site. Outra do Instagram.</p></div></div><div className="report-image-pair">{['website','instagram'].map(type=><button key={type} className="report-thumbnail" onClick={onReportOpen} aria-label={'Ver imagem do '+(type==='website'?'site':'Instagram')}><img src={reportImageUrl(snapshot,type)} alt={'Prévia do relatório do '+(type==='website'?'site':'Instagram')}/></button>)}</div><button className="button primary" onClick={onReportOpen}><FileText size={17}/>Ver imagens e baixar PNG</button><p className="panel-note top-note">O envio semanal usa a última semana completa, de segunda a domingo. A prévia respeita o período selecionado. Campos indisponíveis aparecem com travessão.</p></Panel>
 <div className="stack"><Panel title="Quando receber"><div className="report-preview-heading"><Clock3 className="icon-purple" size={28}/><div><strong>Segunda-feira · 08:00</strong><p>Horário de Brasília</p></div></div><p className="panel-note">{snapshot.demo?'Demonstração: nenhum envio está ativo.':enabled?'Programação semanal ativa na nuvem. O computador pode ficar desligado.':'Programação semanal aguardando ativação.'}</p></Panel>
 <Panel title="Envio por e-mail"><div className="inline-description"><Mail size={24} className="icon-purple"/><p>Um e-mail individual para cada pessoa, com as duas imagens logo abaixo da saudação.</p></div><p className="panel-note">Matheus: henriquestreaming2022@gmail.com<br/>Adriana: adriana_lemos90@hotmail.com</p><p className="panel-note">O status “Aceito pelo Gmail” confirma o envio pelo provedor. Não comprova leitura ou chegada à caixa de entrada.</p></Panel>
 <Panel title="Histórico de envio">{operations?.deliveries?.length?<div className="table-scroll"><table><thead><tr><th>Semana</th><th>Tipo</th><th>Status</th></tr></thead><tbody>{operations.deliveries.map(r=><tr key={r.period_start+r.kind}><td>{r.period_start.split('-').reverse().join('/')}</td><td>{r.kind==='test'?'Teste · 2 imagens':'Semanal · 2 imagens'}</td><td>{labels[r.status]||'Aguardando'}</td></tr>)}</tbody></table></div>:<div className="inline-description"><Bell size={22} className="icon-purple"/><p>Nenhum envio registrado.</p></div>}</Panel></div></div>;
}
