import {useEffect,useState} from 'react';
import {Camera,LogOut,Mail,ShieldCheck} from 'lucide-react';
import {Panel} from '../components/Metrics.jsx';
import {supabase} from '../lib/supabase.js';
import Avatar from '../components/Avatar.jsx';
export default function TeamAccess({session,demo,account}){
 const [feedback,setFeedback]=useState(''),[email,setEmail]=useState(''),[nick,setNick]=useState(''),[password,setPassword]=useState('');
 const self=account.self,profiles=account.profiles;
 useEffect(()=>{if(self?.pending_email)setEmail(self.pending_email);},[self?.pending_email]);
 async function save(kind,event){event.preventDefault();setFeedback('');if(demo){setFeedback('Prévia: a confirmação será enviada ao e-mail vinculado quando o servidor estiver configurado.');return;}try{const result=await account.action({action:kind,email,username:nick,password});setFeedback(result.message||'Confira seu e-mail para confirmar a alteração.');}catch(error){setFeedback(error.message);}finally{setPassword('');}}
 async function photo(event){
  const file=event.target.files?.[0];if(!file)return;setFeedback('');
  if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>3*1024*1024){setFeedback('Escolha uma foto JPG, PNG ou WebP de até 3 MB.');return;}
  if(demo){account.demoAvatar(URL.createObjectURL(file));setFeedback('Foto aplicada somente nesta prévia.');return;}
  try{const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});await account.action({action:'avatar',image:encoded,mime:file.type});setFeedback('Foto de perfil atualizada.');}catch(error){setFeedback(error.message);}finally{event.target.value='';}
 }
 return <>
 <Panel title="Matheus & Adriana"><div className="profile-pair">{profiles.map((profile,index)=><article className="person-profile" key={profile.user_id}><Avatar profile={profile} alt={'Foto de '+profile.display_name}/><div><h3>{profile.display_name}</h3><span>{profile.user_id===session?.user.id||demo&&index===0?'Seu perfil':'Parceira da equipe'}</span></div></article>)}</div><p className="panel-note">Duas contas individuais, o mesmo painel e as mesmas oportunidades.</p></Panel>
 <div className="two-columns view-section"><Panel title="Minha foto"><div className="profile-editor"><Avatar profile={self||profiles[0]} alt="Sua foto de perfil"/><div><label className="button secondary upload-button"><Camera size={17}/>Escolher foto<input type="file" accept="image/jpeg,image/png,image/webp" disabled={account.busy||!demo&&!self} onChange={photo}/></label><p className="panel-note">JPG, PNG ou WebP · até 3 MB</p></div></div></Panel><Panel title="E-mail de recuperação"><p className="profile-email"><Mail size={18}/>{self?.recovery_email||'E-mail ainda não vinculado'}</p><form className="account-form" onSubmit={event=>save('email-request',event)}><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label><label>Senha atual<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label><button className="button secondary" disabled={account.busy}>Vincular e confirmar e-mail</button></form><p className="panel-note">O endereço só será usado após a confirmação enviada para ele.</p></Panel></div>
 <div className="two-columns"><Panel title="Alterar nome de usuário"><form className="account-form" onSubmit={event=>save('username-request',event)}><label>Novo usuário<input value={nick} onChange={e=>setNick(e.target.value)} required minLength={3} maxLength={60} autoComplete="username" placeholder={self?.display_name||'Seu nome de usuário'}/></label><label>Senha atual<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label><button className="button secondary" disabled={account.busy}>Enviar confirmação por e-mail</button></form><p className="panel-note">A troca é concluída quando você confirma o link no e-mail vinculado.</p></Panel><Panel title="Alterar minha senha"><p>Receba um link privado no seu e-mail de recuperação para definir uma nova senha.</p><button className="button secondary view-section" disabled={account.busy||!demo&&!self?.recovery_email} onClick={async()=>{if(demo){setFeedback('Prévia: nenhum e-mail será enviado.');return;}try{const result=await account.action({action:'password-request'});setFeedback(result.message);}catch(error){setFeedback(error.message);}}}>Enviar link para trocar senha</button><p className="panel-note"><ShieldCheck size={15}/> Cada alteração pertence à conta que está conectada.</p>{!demo&&<button className="button secondary view-section" onClick={()=>supabase.auth.signOut({scope:'local'})}><LogOut size={16}/>Sair da conta</button>}</Panel></div>
 <p className="feedback" role="status">{feedback||account.error}</p>
 </>;
}
