import {Monitor,Users,Clock3,Activity,ExternalLink} from 'lucide-react';
import {business} from '../data.js';
import {MetricStrip,Panel,PackageTable} from '../components/Metrics.jsx';
import {WeeklyChart,Funnel} from '../components/Charts.jsx';
import {Distribution,ColumnChart,DataList} from '../components/DataViews.jsx';
import {formatPercent,formatNumber,formatDuration} from '../report.js';
const clickLabels={whatsapp:'WhatsApp',instagram:'Instagram',navigation:'Navegação',service_tab:'Serviços',package_tab:'Categorias',portfolio:'Portfólio',faq:'FAQ',other_button:'Outros botões',other_link:'Outros links'};
export default function Website({snapshot}){
 const {current:c,previous:p}=snapshot;
 return <>
 <a className="source-link" href={business.website} target="_blank" rel="noopener noreferrer">{business.website.replace('https://','')}<ExternalLink size={15}/></a>
 <MetricStrip items={[{label:'Visitas',value:c.visits,previous:p.visits,icon:Monitor},{label:'Visitas vindas do Instagram',value:c.instagramVisits,previous:p.instagramVisits,icon:Users},{label:'Tempo médio',value:c.averageDuration,previous:p.averageDuration,icon:Clock3,format:formatDuration},{label:'Engajamento',value:c.engagementRate,previous:p.engagementRate,icon:Activity,format:formatPercent}]}/>
 <WeeklyChart current={c.dailyVisits} previous={p.dailyVisits}/>
 <div className="three-columns view-section"><Panel title="Origem das visitas"><Distribution items={c.sources}/><DataList items={c.sourceCounts||[]} ranked/><p className="panel-note">Direto: o navegador não informou a origem. A bio deve usar o link abaixo para identificar as visitas do Instagram.</p><a className="bio-tracking-link" href={business.bioUrl} target="_blank" rel="noopener noreferrer">Link para a bio do Instagram<ExternalLink size={14}/></a><code className="bio-url">{business.bioUrl}</code></Panel><Panel title="Dispositivos"><Distribution items={c.devices}/></Panel><Panel title="Estados em destaque"><DataList items={c.regions} percentage ranked/></Panel></div>
 <div className="two-columns"><Panel title="Seções mais vistas"><ColumnChart items={c.sections}/><p className="panel-note">Uma visita pode aparecer em mais de uma seção.</p></Panel><Funnel data={c}/></div>
 <div className="three-columns"><Panel title="Tempo de permanência"><ColumnChart items={c.durations} percentage/></Panel><Panel title="Profundidade de rolagem"><ColumnChart items={c.scroll}/></Panel><Panel title="Desempenho do site"><dl className="detail-list">{c.webVitals.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}<div><dt>Erros JavaScript</dt><dd>{formatNumber(c.jsErrors)}</dd></div></dl></Panel></div>
 <div className="two-columns"><Panel title="Interesse por pacote"><PackageTable packages={c.packages}/></Panel><Panel title="Público e horários"><dl className="detail-list"><div><dt>Novos visitantes</dt><dd>{formatNumber(c.newVisitors)}</dd></div><div><dt>Voltaram ao site</dt><dd>{formatNumber(c.returningVisitors)}</dd></div><div><dt>Rejeição</dt><dd>{formatPercent(c.bounceRate)}</dd></div><div><dt>Dia de maior movimento</dt><dd>{c.peakDay||'Não disponível'}</dd></div><div><dt>Horário de pico</dt><dd>{c.peakTime||'Não disponível'}</dd></div></dl></Panel></div>
 <details className="advanced-data"><summary>Ver detalhes de navegação e localidades</summary><div className="three-columns view-section"><Panel title="Navegadores"><DataList items={c.browsers} percentage/></Panel><Panel title="Sistemas operacionais"><DataList items={c.operatingSystems} percentage/></Panel><Panel title="Cliques por tipo"><DataList items={(c.buttonClicks||[]).map(([label,value])=>[clickLabels[label]||'Outros',value])} ranked/></Panel></div><div className="three-columns"><Panel title="Páginas vistas"><DataList items={c.pages}/></Panel><Panel title="Países"><DataList items={c.countries}/></Panel><Panel title="Cidades do Brasil"><DataList items={c.cities}/><p className="panel-note">Localização aproximada da conexão, quando informada pela infraestrutura. Não utiliza GPS. Geolocalização por <a href="https://db-ip.com" target="_blank" rel="noopener noreferrer">DB-IP</a>, base de outubro de 2026, com precisão e cobertura limitadas.</p></Panel></div></details>
 </>;
}

