import {useMemo,useState} from 'react';
import {MessageCircle,Users,CheckCheck,UserCheck} from 'lucide-react';
import {MetricStrip,Panel} from '../components/Metrics.jsx';
import {leadStages} from '../whatsapp.js';
import {Distribution,DataList} from '../components/DataViews.jsx';
import {packageLabels,serviceLabels,stateLabels,summarizeSales,summarizeSalesPeriod} from '../sales.js';
import ConfirmContact from '../components/ConfirmContact.jsx';
import ConfirmArrival from '../components/ConfirmArrival.jsx';
import OpportunityEditor from '../components/OpportunityEditor.jsx';
import BrazilMap from '../components/BrazilMap.jsx';
export default function WhatsAppPage({snapshot,leads,onStageChange,onConfirm,onConfirmLink,onPackageChange,onClientSave,busy=false,reference='',readOnly=false,crmAvailable=true}){
 const [view,setView]=useState('board'),[editing,setEditing]=useState(null),[filter,setFilter]=useState('all');
 const sales=useMemo(()=>snapshot.demo?summarizeSales(leads):summarizeSalesPeriod(leads,snapshot.period),[leads,snapshot.demo,snapshot.period]);
 const clients=useMemo(()=>Object.values(leads.filter(lead=>lead.client_id).reduce((all,lead)=>{const entry=all[lead.client_id]||(all[lead.client_id]={id:lead.client_id,label:lead.client_label||'Cliente '+lead.client_id.slice(-6),orders:0,won:0,state:lead.customer_state});entry.orders++;entry.won+=lead.stage==='won'?1:0;if(lead.client_label)entry.label=lead.client_label;return all;},{})),[leads]);
 const shown=leads.filter(lead=>filter==='all'||(lead.service_category||'unknown')===filter);
 const card=(lead,i)=><article className="deal-card" key={lead.id}><h3>{lead.client_label||((snapshot.demo?'Exemplo':'Oportunidade')+' '+lead.reference.slice(-6))}</h3><code>{lead.reference}</code><p className="deal-category">{serviceLabels[lead.service_category]||serviceLabels.unknown}</p><label>Pacote negociado<select disabled={busy||readOnly||!crmAvailable} value={lead.selected_package||String(lead.package).toUpperCase()} aria-label={'Pacote da oportunidade '+(i+1)} onChange={e=>onPackageChange(lead.id,e.target.value)}>{Object.entries(packageLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{lead.custom_package_name&&<p>{lead.custom_package_name}</p>}<p>{lead.customer_city&&lead.customer_city+' · '}{stateLabels[lead.customer_state]||'Região não informada'}</p><p>{lead.received}</p><label>Etapa<select disabled={busy||readOnly} aria-label={'Etapa da oportunidade '+(i+1)} value={lead.stage} onChange={e=>onStageChange(lead.id,e.target.value)}>{leadStages.map(stage=><option key={stage.id} value={stage.id}>{stage.label}</option>)}</select></label><button className="button secondary" disabled={readOnly||!crmAvailable} onClick={()=>setEditing(lead)}>Dados do cliente</button><small>{lead.client_id?'Cliente identificado':'Identificação pendente'}</small></article>;
 const mapSnapshot={...snapshot,demo:false,current:{...snapshot.current,stateVisitors:Object.fromEntries(sales.salesByState),geoUniqueVisitors:sales.won,uniqueVisitors:sales.won,geographySource:'Estado informado no atendimento'}};
 return <>
 {reference&&<ConfirmArrival reference={reference} demo={snapshot.demo} onConfirm={onConfirmLink} readOnly={readOnly||!crmAvailable}/>}
 <MetricStrip items={[{label:'Oportunidades recebidas',value:sales.opportunities,icon:MessageCircle,color:'mint'},{label:'Clientes identificados',value:crmAvailable?sales.clients:null,icon:Users},{label:'Vendas fechadas',value:sales.won,icon:CheckCheck,color:'mint'},{label:'Clientes que compraram',value:crmAvailable?sales.buyers:null,icon:UserCheck,color:'mint'}]}/>
 <p className="panel-note sales-period-note">{snapshot.demo?'Demonstração: exemplos que você pode editar.':'Recebimentos por data de chegada; vendas e compradores por data de fechamento. O quadro e o cadastro de clientes reúnem todo o histórico.'} {crmAvailable&&sales.unidentified>0&&`${sales.unidentified} oportunidade(s) recebida(s) ainda sem identificação do cliente.`}</p>
 {!crmAvailable&&<p className="connection-notice" role="status">As oportunidades existentes são reais. O cadastro de clientes, serviços e regiões será ativado após conectar o servidor e aplicar a atualização do banco.</p>}
 <Panel title="Oportunidades do site" action={<div className="button-row"><button className="button secondary" aria-pressed={view==='board'} onClick={()=>setView('board')}>Quadro</button><button className="button secondary" aria-pressed={view==='list'} onClick={()=>setView('list')}>Lista</button></div>}>
 <label className="service-filter">Filtrar por serviço<select aria-label="Filtrar por serviço" value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">Todos os serviços</option>{Object.entries(serviceLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
 {view==='board'?<div className="sales-board">{leadStages.map(stage=><section className={'sales-column stage-'+stage.id} key={stage.id}><header><h3>{stage.label}</h3><span>{shown.filter(lead=>lead.stage===stage.id).length}</span></header>{shown.filter(lead=>lead.stage===stage.id).map(card)}{!shown.some(lead=>lead.stage===stage.id)&&<p className="empty-stage">Nenhuma oportunidade</p>}</section>)}</div>:<div className="deal-list">{shown.map(card)}</div>}
 {!leads.length&&<p className="panel-note">Confirme uma mensagem usando o link recebido no WhatsApp. Ela aparecerá aqui com a referência e o pacote de origem.</p>}
 </Panel>
 <section className="two-columns view-section" aria-label="Serviços e pacotes vendidos"><Panel title="Quais serviços mais vendem"><Distribution items={crmAvailable?sales.salesByService:[]} percentage={false}/><p className="panel-note">Vendas fechadas no período, por serviço registrado no atendimento.</p></Panel><Panel title="Pacotes fechados"><div className="table-scroll"><table><thead><tr><th>Pacote</th><th>Vendas</th></tr></thead><tbody>{sales.salesByPackage.map(row=><tr key={row.package}><th>{packageLabels[row.package]}</th><td className="positive">{row.won}</td></tr>)}</tbody></table></div>{sales.customPackages.length>0&&<><h3 className="custom-packages-heading">Personalizados criados por vocês</h3><DataList items={sales.customPackages}/></>}</Panel></section>
 <section className="sales-geography view-section" aria-label="Regiões que compram"><BrazilMap snapshot={mapSnapshot} title="Onde nossos pacotes são comprados" unit="vendas" context="Vendas fechadas por estado"/><Panel title="Regiões com mais compras"><DataList items={sales.salesByRegion} ranked/><p className="panel-note">{sales.unknownState} venda(s) sem estado informado. {sales.unidentifiedWon} venda(s) sem cliente identificado.</p>{sales.salesByCity.length>0&&<><h3 className="custom-packages-heading">Cidades</h3><DataList items={sales.salesByCity.slice(0,5)} ranked/></>}</Panel></section>
 <Panel title="Cadastro de clientes" className="view-section" action={<span className="panel-context">{crmAvailable?clients.length+' clientes identificados':'Aguardando integração'}</span>}><div className="table-scroll"><table><thead><tr><th>Cliente</th><th>Estado</th><th>Pedidos</th><th>Vendas fechadas</th></tr></thead><tbody>{clients.map(client=><tr key={client.id}><th>{client.label}</th><td>{stateLabels[client.state]||'Não informado'}</td><td>{client.orders}</td><td>{client.won}</td></tr>)}</tbody></table></div>{!clients.length&&<p className="empty-explanation">Ao informar o telefone nos dados do pedido, o cliente entra neste cadastro. Pedidos com o mesmo telefone são agrupados.</p>}<p className="panel-note">Total identificado em todo o histórico. Compras por região contam vendas; compradores únicos contam pessoas identificadas.</p></Panel>
 <details className="advanced-data view-section"><summary>Confirmar pelo código e telefone</summary><ConfirmContact demo={snapshot.demo} onConfirm={onConfirm} busy={busy||readOnly}/></details>
 <p className="page-footnote">Abrir o link não confirma envio. Só a equipe pode confirmar a mensagem recebida. Fechamento registrado pela equipe não comprova pagamento.</p>
 {editing&&<OpportunityEditor key={editing.id} lead={editing} onSave={onClientSave} onClose={()=>setEditing(null)} busy={busy} demo={snapshot.demo}/>}
 </>;
}
