import {MessageCircle,FileText,Send,CheckCheck,ShieldCheck} from 'lucide-react';
import {MetricStrip,Panel} from '../components/Metrics.jsx';
import {leadStages} from '../whatsapp.js';
import ConfirmContact from '../components/ConfirmContact.jsx';
export default function WhatsAppPage({snapshot,leads,onStageChange,onConfirm,busy=false}){
 const {current,previous}=snapshot;
 return <><MetricStrip items={[
 {label:'Contatos vindos do site',value:current.websiteReceivedContacts,previous:previous.websiteReceivedContacts,icon:MessageCircle,color:'mint'},
 {label:'Orçamentos pelo site',value:current.websiteQuoteRequests,previous:previous.websiteQuoteRequests,icon:FileText},
 {label:'Orçamentos enviados',value:current.quoteSent,previous:previous.quoteSent,icon:Send},
 {label:'Negócios fechados',value:current.closed,previous:previous.closed,icon:CheckCheck,color:'mint'}]}/>
 <Panel title="Como identificamos a origem"><div className="whatsapp-guide"><div><span className="step-number">01</span><h3>Referência do site</h3><p>O botão inclui um código registrado no servidor. Depois de receber a mensagem no WhatsApp, vocês registram a referência no formulário abaixo.</p></div><div><span className="step-number">02</span><h3>Contatos distintos</h3><p>Cinco mensagens da mesma pessoa contam como um contato na semana. Registrar novamente a mesma referência não duplica o resultado.</p></div><div><span className="step-number">03</span><h3>Orçamento confirmado</h3><p>Marquem “Solicitou orçamento” depois de conferir a conversa. As duas contas compartilham a etapa; avançar ou perder a oportunidade preserva o histórico.</p></div></div><p className="panel-note top-note">Mensagens de outros canais, códigos apagados, expirados ou compartilhados entre pessoas diferentes ficam fora da atribuição confirmada. No WhatsApp comum, o registro é uma confirmação feita pela equipe, após conferir a mensagem recebida.</p></Panel>
 <ConfirmContact demo={snapshot.demo} onConfirm={onConfirm} busy={busy}/>
 <Panel title={snapshot.demo?'Oportunidades · experimentar o fluxo':'Oportunidades vindas do site'} className="overview-packages">
 {snapshot.demo&&<p className="panel-note top-note">Quatro contatos fictícios para experimentar as etapas.</p>}
 {leads.length?<><div className="table-scroll"><table><thead><tr><th>Oportunidade</th><th>Pacote</th><th>Origem</th><th>Recebido</th><th>Etapa</th></tr></thead><tbody>{leads.map((lead,i)=><tr key={lead.id}><th scope="row">{snapshot.demo?'Exemplo':'Contato'} {i+1}<br/><span className="reference-code">{lead.reference}</span></th><td>{lead.package}</td><td>Site · {lead.source.replace(/^Site · /,'')}</td><td>{lead.received}</td><td><select className="lead-stage" disabled={busy} aria-label={'Etapa do contato '+(i+1)} value={lead.stage} onChange={e=>onStageChange(lead.id,e.target.value)}>{leadStages.map(stage=><option key={stage.id} value={stage.id}>{stage.label}</option>)}</select></td></tr>)}</tbody></table></div><p className="lead-demo-note">{snapshot.demo?'Alterações locais nesta demonstração. Não há clientes reais.':'O código permite localizar a conversa no WhatsApp. Exibimos até 200 oportunidades recentes do período; as métricas usam o histórico completo.'}</p></>:<p className="empty-explanation">Nenhuma oportunidade atribuída ao site neste período. Os contatos aparecerão depois de registrar uma mensagem recebida com referência válida.</p>}
 </Panel><div className="two-columns overview-packages"><Panel title="O que o painel guarda"><div className="inline-description"><ShieldCheck className="icon-mint"/><p>Referência, pacote, origem e etapa. Identificadores de contatos são pseudonimizados; nomes, telefones e textos de conversas não são exibidos nem armazenados na coleta.</p></div></Panel><Panel title="Como interpretar"><p>Contatos contam mensagens recebidas com referência válida na semana. Orçamentos contam pessoas das oportunidades recebidas naquele período, com solicitação confirmada no histórico.</p><p className="panel-note">As unidades são diferentes de visitas e cliques. O cliente pode chegar ao site numa semana e conversar na seguinte.</p></Panel></div></>;
}
